# This is a basic workflow to help you get started with Actions

name: build-and-publish

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab (nested under on)
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow builds and then deploys
  build:
    # The type of runner that the job will run on (stretch goal: parallel runners for OS testing)
    # runs-on: ubuntu-latest
    runs-on: macos-latest
    
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # download and install dependencies (e.g. pandoc, pdflatex)
      # make website
  
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      # Hypothesis: actions is marketplace for GHA checkout will clone 
      # in new directory the contents of main
      - uses: actions/checkout@v2


      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Debugging where we are: $GITHUB_WORKSPACE
          pwd
          ls
          ls -l $GITHUB_WORKSPACE

      - name: Download and install dependencies
        run: |
          /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
          # https://formulae.brew.sh/cask/mactex-no-gui has a link to
          # http://mirror.ctan.org/systems/mac/mactex/mactex-20210328.pkg which
          # is a 404. At http://mirror.ctan.org/systems/mac/mactex/ you can see
          # this was updated. Try just fetching and installing that .pkg
          # directly as a workaround until brew formula fixed.
          wget -q "https://mirrors.concertpass.com/tex-archive/systems/mac/mactex/mactex-20220321.pkg"
          # https://apple.stackexchange.com/questions/72226/installing-pkg-with-terminal
          sudo installer -pkg ./mactex-20220321.pkg -target /
          echo "/usr/local/opt" >> $GITHUB_PATH
          echo "/Library/TeX/texbin" >> $GITHUB_PATH
          brew install pandoc

      - name: Create copy of website using makefile
        run: |
          make index; make website; make index; make website

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./generated
          publish_branch: published

